-- AlterTable
ALTER TABLE "Purchases" ALTER COLUMN "registedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Sells" ALTER COLUMN "registedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "WarehouseUsers" ALTER COLUMN "registerAt" SET DEFAULT CURRENT_TIMESTAMP;
