-- AlterTable
ALTER TABLE "WarehouseAdmin" ALTER COLUMN "name" SET DEFAULT 'Juan',
ALTER COLUMN "lastName" SET DEFAULT 'Pelarmo',
ALTER COLUMN "roleId" SET DEFAULT 1,
ALTER COLUMN "bornAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dui" SET DEFAULT '000000000',
ALTER COLUMN "state" SET DEFAULT true,
ALTER COLUMN "registerAt" SET DEFAULT CURRENT_TIMESTAMP;
